version: "3.9"

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=production
    
  frontend:
    build: ./frontend/interview-pre-ai-app
    ports:
      - "3000:80"